plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.hilt)
    alias(libs.plugins.ksp)
    alias(libs.plugins.kover)
    alias(libs.plugins.baselineprofile)
}

val qandeelVersionCode = providers.gradleProperty("qandeel.versionCode").get().toInt()

android {
    namespace = "dev.sadakat.qandeel"
    compileSdk = 37

    defaultConfig {
        applicationId = "dev.sadakat.qandeel"
        minSdk = 26
        targetSdk = 36
        // gradle.properties holds the release; the phone app's versionCode ends in 0 (see there).
        versionCode = qandeelVersionCode * 10
        versionName = providers.gradleProperty("qandeel.versionName").get()

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        // The upload key from the root build (keystore.properties or QIT_UPLOAD_*), when present.
        @Suppress("UNCHECKED_CAST")
        (rootProject.extra["uploadSigning"] as Map<String, String>?)?.let { key ->
            create("release") {
                storeFile = file(key.getValue("storeFile"))
                storePassword = key.getValue("storePassword")
                keyAlias = key.getValue("keyAlias")
                keyPassword = key.getValue("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            signingConfig = signingConfigs.findByName("release")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
        // The baseline profile plugin derives these from release to generate and benchmark on a
        // device; they are never published, so the debug key lets them install.
        configureEach {
            if (name == "nonMinifiedRelease" || name == "benchmarkRelease") {
                signingConfig = signingConfigs.getByName("debug")
            }
        }
    }
    // Built-in Kotlin takes its jvmTarget from targetCompatibility.
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    testOptions {
        unitTests.isIncludeAndroidResources = true
    }
    buildFeatures {
        compose = true
        // AboutScreen shows the version name.
        buildConfig = true
    }
    lint {
        checkReleaseBuilds = false
        abortOnError = true
        warningsAsErrors = false
        disable += setOf("GradleDependency", "NewerVersionAvailable", "AndroidGradlePluginVersion", "OldTargetApi")
    }
}

hilt {
    enableAggregatingTask = false
}

dependencies {
    implementation(project(":core:data"))
    // The UI, shared with iOS: the phone app hosts it (MainActivity) and provides its ports.
    implementation(project(":shared"))

    // Startup: the baseline profile generated by :baselineprofile, installed on sideloads too.
    implementation(libs.androidx.profileinstaller)
    baselineProfile(project(":baselineprofile"))

    // Core Android
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)

    // Compose
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)

    // Wearable Data Layer
    implementation(libs.play.services.wearable)

    // Media3 for audio playback
    implementation(libs.media3.exoplayer)
    implementation(libs.media3.session)

    // Lifecycle for collectAsStateWithLifecycle
    implementation(libs.androidx.lifecycle.runtime.compose)

    // Coroutines
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.coroutines.play.services)

    // Hilt
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)

    // DataStore
    implementation(libs.datastore.preferences)

    // Serialization
    implementation(libs.kotlinx.serialization.json)

    // Testing: JVM unit tests (fakes from :core:testing) and Robolectric for the activity and services
    testImplementation(project(":core:testing"))
    // Hilt-injected Android entry points (services) under Robolectric
    testImplementation(libs.hilt.android.testing)
    kspTest(libs.hilt.compiler)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.core.ktx)
    testImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
}
